import {NgModule} from '@angular/core';
import {BrowserModule} from '@angular/platform-browser';

import {AppRoutingModule} from './app-routing.module';
import {AppComponent} from './app.component';
import {
  AlphabetSliderComponent,
  CustomCombineLabelsFunctionSliderComponent,
  CustomDisplayFunctionSliderComponent,
  CustomHtmlDisplayFunctionSliderComponent,
  CustomLegendFunctionSliderComponent,
  CustomScaleSliderComponent,
  CustomTicksLegendSliderComponent,
  CustomTicksSliderComponent,
  DateSliderComponent,
  DisabledNormalisationSliderComponent,
  DisabledSliderComponent,
  DraggableRangeOnlySliderComponent,
  DraggableRangeSliderComponent,
  DynamicallyCreatedSlidersComponent,
  DynamicColorSelectionBarSliderComponent,
  DynamicOptionsSliderComponent,
  DynamicPointerColorSliderComponent,
  DynamicTickColorSliderComponent,
  FloatingPointSliderComponent,
  IntermediateTicksSliderComponent,
  IntermediateTicksValuesRangeSliderComponent,
  LimitedRangeSliderComponent,
  LimitedSliderComponent,
  LogScaleSliderComponent,
  ManualRefreshSliderComponent,
  NoSwitchingRangeSliderComponent,
  PushRangeSliderComponent,
  RangeSliderComponent,
  ReactiveFormRangeSliderComponent,
  ReactiveFormSimpleSliderComponent,
  ReadOnlySliderComponent,
  RightToLeftSliderComponent,
  SelectionBarAtEndSliderComponent,
  SelectionBarFromValueSliderComponent,
  SelectionBarGradientSliderComponent,
  SelectionBarSliderComponent,
  SimpleSliderComponent,
  SteppedSliderComponent,
  StyledSliderComponent,
  TicksCustomTooltipsSliderComponent,
  TicksSliderComponent,
  TicksTooltipsSliderComponent,
  TicksValuesRangeSliderComponent,
  TicksValuesSliderComponent,
  TicksValuesTooltipsSliderComponent,
  TriggerFocusSliderComponent,
  UserEventsSliderComponent,
  VerticalSlidersComponent
} from './snippets';
import {HeaderComponent} from './header.component';
import {HomeComponent} from './home.component';
import {DemosComponent} from './demos.component';

@NgModule({
  declarations: [
    AppComponent,
    HeaderComponent,
    HomeComponent,
    DemosComponent,
    AlphabetSliderComponent,
    CustomCombineLabelsFunctionSliderComponent,
    CustomDisplayFunctionSliderComponent,
    CustomHtmlDisplayFunctionSliderComponent,
    CustomLegendFunctionSliderComponent,
    CustomScaleSliderComponent,
    CustomTicksLegendSliderComponent,
    CustomTicksSliderComponent,
    DateSliderComponent,
    DisabledNormalisationSliderComponent,
    DisabledSliderComponent,
    DraggableRangeOnlySliderComponent,
    DraggableRangeSliderComponent,
    DynamicColorSelectionBarSliderComponent,
    DynamicOptionsSliderComponent,
    DynamicPointerColorSliderComponent,
    DynamicTickColorSliderComponent,
    DynamicallyCreatedSlidersComponent,
    FloatingPointSliderComponent,
    IntermediateTicksSliderComponent,
    IntermediateTicksValuesRangeSliderComponent,
    LimitedRangeSliderComponent,
    LimitedSliderComponent,
    LogScaleSliderComponent,
    ManualRefreshSliderComponent,
    NoSwitchingRangeSliderComponent,
    PushRangeSliderComponent,
    RangeSliderComponent,
    ReactiveFormRangeSliderComponent,
    ReactiveFormSimpleSliderComponent,
    ReadOnlySliderComponent,
    RightToLeftSliderComponent,
    SelectionBarAtEndSliderComponent,
    SelectionBarFromValueSliderComponent,
    SelectionBarGradientSliderComponent,
    SelectionBarSliderComponent,
    SimpleSliderComponent,
    SteppedSliderComponent,
    StyledSliderComponent,
    TicksCustomTooltipsSliderComponent,
    TicksSliderComponent,
    TicksTooltipsSliderComponent,
    TicksValuesRangeSliderComponent,
    TicksValuesSliderComponent,
    TicksValuesTooltipsSliderComponent,
    TriggerFocusSliderComponent,
    UserEventsSliderComponent,
    VerticalSlidersComponent
  ],
  imports: [
    BrowserModule,
    AppRoutingModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule {
}
